image:
  repository: docker.io/guscontre1/ocp-dog-frontend
  tag: "3"

service:
  port: 80
  targetPort: 8080

config:
  FRONTEND_API_URL: http://ocp-dog-frontend-api.apps.rm1.0a51.p1.openshiftapps.com
